var express = require('express');
var router = express.Router();


let cities = [
  {city :"Alaminos", province :"Pangasinan"},
  {city :"Angeles ity", province :"Pampanga"},
  {city :"Antipolo", province :"Rizal"},
  {city :"Bacolod", province :"Negros Occidental"},
  {city :"Bacoor", province :"Cavite"},
  {city :"Bago", province :"Negros Occidental"},
  {city :"Baguio", province :"Benguet"},
  {city :"Bais", province :"Negros Oriental"},
  {city :"Balanga", province :"Bataan"},
  {city :"Batac", province :"Ilocos Norte"},
  {city :"Batangas ity", province :"Batangas"},
  {city :"Bayawan", province :"Negros Oriental"},
  {city :"Baybay", province :"Leyte"},
  {city :"Bayugan", province :"Agusan del Sur"},
  {city :"Biñan", province :"Laguna"},
  {city :"Bislig", province :"Surigao del Sur"},
  {city :"Bogo", province :"Cebu"},
  {city :"Borongan", province :"Eastern Samar"},
  {city :"Butuan", province :"Agusan del Norte"},
  {city :"Cabadbaran", province :"Agusan del Norte"},
  {city :"Cabanatuan", province :"Nueva Ecija"},
  {city :"Cabuyao", province :"Laguna"},
  {city :"Cadiz", province :"Negros Occidental"},
  {city :"Cagayan de Oro", province :"Misamis Oriental"},
  {city :"Calaca", province :"Batangas"},
  {city :"Calamba", province :"Laguna"},
  {city :"Calapan", province :"Oriental Mindoro"},
  {city :"Calbayog", province :"Samar"},
  {city :"Caloocan", province :"NCR"},
  {city :"Candon", province :"Ilocos Sur"},
  {city :"Canlaon", province :"Negros Oriental"},
  {city :"Carcar", province :"Cebu"},
  {city :"Catbalogan", province :"Samar"},
  {city :"Cauayan", province :"Isabela"},
  {city :"Cavite ity", province :"Cavite"},
  {city :"Cebu ity", province :"Cebu"},
  {city :"Cotabato ity", province :"Maguindanao del Norte"},
  {city :"Dagupan", province :"Pangasinan"},
  {city :"Danao", province :"Cebu"},
  {city :"Dapitan", province :"Zamboanga del Norte"},
  {city :"Dasmariñas", province :"Cavite"},
  {city :"Davao ity", province :"Davao del Sur"},
  {city :"Digos", province :"Davao del Sur"},
  {city :"Dipolog", province :"Zamboanga del Norte"},
  {city :"Dumaguete", province :"Negros Oriental"},
  {city :"El Salvador", province :"Misamis Oriental"},
  {city :"Escalante", province :"Negros Occidental"},
  {city :"Gapan", province :"Nueva Ecija"},
  {city :"General Santos", province :"South Cotabato"},
  {city :"General Trias", province :"Cavite"},
  {city :"Gingoog", province :"Misamis Oriental"},
  {city :"Guihulngan", province :"Negros Oriental"},
  {city :"Himamaylan", province :"Negros Occidental"},
  {city :"Ilagan", province :"Isabela"},
  {city :"Iligan", province :"Lanao del Norte"},
  {city :"Iloilo ity", province :"Iloilo"},
  {city :"Imus", province :"Cavite"},
  {city :"Iriga", province :"Camarines Sur"},
  {city :"Isabela", province :"Basilan"},
  {city :"Kabankalan", province :"Negros Occidental"},
  {city :"Kidapawan", province :"Cotabato"},
  {city :"Koronadal", province :"South Cotabato"},
  {city :"La Carlota", province :"Negros Occidental"},
  {city :"Lamitan", province :"Basilan"},
  {city :"Laoag", province :"Ilocos Norte"},
  {city :"Lapu-Lapu ity", province :"Cebu"},
  {city :"Las Piñas", province :"NCR"},
  {city :"Legazpi", province :"Albay"},
  {city :"Ligao", province :"Albay"},
  {city :"Lipa", province :"Batangas"},
  {city :"Lucena", province :"Quezon"},
  {city :"Maasin", province :"Southern Leyte"},
  {city :"Mabalacat", province :"Pampanga"},
  {city :"Makati", province :"NCR"},
  {city :"Malabon", province :"NCR"},
  {city :"Malaybalay", province :"Bukidnon"},
  {city :"Malolos", province :"Bulacan"},
  {city :"Mandaluyong", province :"NCR"},
  {city :"Mandaue", province :"Cebu"},
  {city :"Manila", province :"NCR"},
  {city :"Marawi", province :"Lanao del Sur"},
  {city :"Marikina", province :"NCR"},
  {city :"Masbate ity", province :"Masbate"},
  {city :"Mati", province :"Davao Oriental"},
  {city :"Meycauayan", province :"Bulacan"},
  {city :"Muñoz", province :"Nueva Ecija"},
  {city :"Muntinlupa", province :"NCR"},
  {city :"Naga", province :"Camarines Sur"},
  {city :"Naga", province :"Cebu"},
  {city :"Navotas", province :"NCR"},
  {city :"Olongapo", province :"Zambales"},
  {city :"Ormoc", province :"Leyte"},
  {city :"Oroquieta", province :"Misamis Occidental"},
  {city :"Ozamiz", province :"Misamis Occidental"},
  {city :"Pagadian", province :"Zamboanga del Sur"},
  {city :"Palayan", province :"Nueva Ecija"},
  {city :"Panabo", province :"Davao del Norte"},
  {city :"Parañaque", province :"NCR"},
  {city :"Pasay", province :"NCR"},
  {city :"Pasig", province :"NCR"},
  {city :"Passi", province :"Iloilo"},
  {city :"Puerto Princesa", province :"Palawan"},
  {city :"Quezon ity", province :"NCR"},
  {city :"Roxas", province :"Capiz"},
  {city :"Sagay", province :"Negros Occidental"},
  {city :"Samal", province :"Davao del Norte"},
  {city :"San Carlos", province :"Negros Occidental"},
  {city :"San Carlos", province :"Pangasinan"},
  {city :"San Fernando", province :"La Union"},
  {city :"San Fernando", province :"Pampanga"},
  {city :"San Jose", province :"Nueva Ecija"},
  {city :"San Jose del Monte", province :"Bulacan"},
  {city :"San Juan", province :"NCR"},
  {city :"San Pablo", province :"Laguna"},
  {city :"San Pedro", province :"Laguna"},
  {city :"Santa Rosa", province :"Laguna"},
  {city :"Santo Tomas", province :"Batangas"},
  {city :"Santiago", province :"Isabela"},
  {city :"Silay", province :"Negros Occidental"},
  {city :"Sipalay", province :"Negros Occidental"},
  {city :"Sorsogon ity", province :"Sorsogon"},
  {city :"Surigao ity", province :"Surigao del Norte"},
  {city :"Tabaco", province :"Albay"},
  {city :"Tabuk", province :"Kalinga"},
  {city :"Tacloban", province :"Leyte"},
  {city :"Tacurong", province :"Sultan Kudarat"},
  {city :"Tagaytay", province :"Cavite"},
  {city :"Tagbilaran", province :"Bohol"},
  {city :"Taguig", province :"NCR"},
  {city :"Tagum", province :"Davao del Norte"},
  {city :"Talisay", province :"Cebu"},
  {city :"Talisay", province :"Negros Occidental"},
  {city :"Tanauan", province :"Batangas"},
  {city :"Tandag", province :"Surigao del Sur"},
  {city :"Tangub", province :"Misamis Occidental"},
  {city :"Tanjay", province :"Negros Oriental"},
  {city :"Tarlac ity", province :"Tarlac"},
  {city :"Tayabas", province :"Quezon"},
  {city :"Toledo", province :"Cebu"},
  {city :"Trece Martires", province :"Cavite"},
  {city :"Tuguegarao", province :"Cagayan"},
  {city :"Urdaneta", province :"Pangasinan"},
  {city :"Valencia", province :"Bukidnon"},
  {city :"Valenzuela", province :"NCR"},
  {city :"Victorias", province :"Negros Occidental"},
  {city :"Vigan", province :"Ilocos Sur"},
  {city :"Zamboanga ity", province :"Zamboanga del Sur"}      
];


router.get('/', (req, res, next) => {
  res.send(cities);
});

module.exports = router;
